brand: "SMS Idea"
address: "Pune, India"
email: "contact@smsidea.in"
phone: "+91-00000-00000"
social:
  twitter: "https://twitter.com/smsideain"
  linkedin: "https://linkedin.com/company/smsidea"
  github: "https://github.com/smsideain"
