name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build (includes sitemap & RSS)
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Report Build Status
        run: |
          if [ "${{ needs.build.outputs.build-status }}" == "success" ]; then
            echo "✅ Build completed successfully"
          else
            echo "❌ Build failed with status: ${{ needs.build.outputs.build-status }}"
            exit 1
          fi

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4